name: CI for general build

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        arch: [ arm64 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: ${{matrix.arch}}
